In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("iris1.csv")
data.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
X = data.iloc[:,0:4].values
Y = data.iloc[:,4].values


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [5]:
train_x,test_x,train_y,test_y = train_test_split(X,Y,test_size=0.20,stratify=Y,random_state=5)
test_x

array([[5.5, 3.5, 1.3, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [5. , 2.3, 3.3, 1. ],
       [6.9, 3.1, 5.1, 2.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.9, 1.3, 0.4],
       [5.5, 2.4, 3.8, 1.1],
       [5.6, 2.7, 4.2, 1.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [7.7, 2.6, 6.9, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [6.7, 3.3, 5.7, 2.1],
       [6.4, 2.7, 5.3, 1.9],
       [7.2, 3. , 5.8, 1.6],
       [4.6, 3.2, 1.4, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [5. , 3.2, 1.2, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.1, 3. , 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.4, 3.3, 1. ],
       [5.8, 4. , 1.2, 0.2],
       [6.2, 3.4, 5.4, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [6.4, 3.2, 4.5, 1.5],
       [5.7, 3. , 4.2, 1.2]])

In [6]:
test_y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [7]:
# sc = StandardScaler()
# train_x = sc.fit_transform(train_x)
# test_x = sc.transform(test_x)
# Le = LabelEncoder()
# train_y = Le.fit_transform(train_y)
# test_y = Le.fit_transform(test_y)

In [8]:
import xgboost as xgb
from xgboost import XGBClassifier

In [9]:
classifier = XGBClassifier(max_depth=4,gamma=0.1,reg_alpha=0.1,reg_lambda=0.1,learning_rate=0.1)

In [10]:
classifier.fit(train_x,train_y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0.1,
              learning_rate=0.1, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0.1, reg_lambda=0.1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [11]:
import pickle
pickle.dump(classifier,open('xgb_iris.pkl','wb'))

In [12]:
cl = pickle.load(open('xgb_iris.pkl','rb'))
test_x[0]

array([5.5, 3.5, 1.3, 0.2])

In [13]:
y_pred = cl.predict(test_x)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [14]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [15]:
confusion_matrix(test_y,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  8]], dtype=int64)

In [16]:
print(classification_report(test_y,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.83      1.00      0.91        10
 Iris-virginica       1.00      0.80      0.89        10

       accuracy                           0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30



In [17]:
accuracy_score(test_y,y_pred)

0.9333333333333333

In [18]:
from sklearn.model_selection import cross_val_score,GridSearchCV

In [19]:
accuracy = cross_val_score(estimator = classifier,X=train_x,y=train_y,cv=5,n_jobs=-1)

In [20]:
accuracy

array([0.95833333, 1.        , 0.95833333, 0.91666667, 0.91666667])

In [21]:
accuracy.mean()

0.95

In [22]:
accuracy.std()

0.0311804782231162

In [23]:
h_parameter = {'max_depth':[4,5,6,7],"learning_rate":[0.1,0.2,0.3,0.4,0.5],'booster':['gbtree','gblinear']
               ,'gamma':[0.1,0.2,0.3,0.4,0.5],'importance_type':["gain","weight", "cover", "total_gain"],'reg_alpha':[0.1,0.2,0.3], 'reg_lambda':[0.1,0.2,0.3]}
clf = GridSearchCV(estimator=classifier,param_grid=h_parameter, cv=10,n_jobs=-1,return_train_score=True)

In [24]:
clf.fit(train_x,train_y)

GridSearchCV(cv=10, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0.1,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=4, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='multi:softprob',
                                     random_state=0, reg_alpha=0.1,
                                     reg_lambda=0.1, sc...
             iid='deprecated', n_jobs=-1,
             param_grid={'booster': ['gbtree', 'gblinear'],
                         'gamma': [0.1, 0.2, 0.3, 0.4, 0.5],
                         'importance_type': ['gain', 'weight', 'cover',
                                             'total_gain'],
                      

In [25]:
clf.best_params_

{'booster': 'gbtree',
 'gamma': 0.3,
 'importance_type': 'gain',
 'learning_rate': 0.1,
 'max_depth': 4,
 'reg_alpha': 0.3,
 'reg_lambda': 0.1}

In [26]:
clf.best_score_

0.9499999999999998

In [27]:
clf.scorer_(estimator=classifier,X=train_x,y=train_y)

1.0

In [30]:
from mlxtend.plotting import plot_decision_regions

In [31]:
# plot_decision_regions(X=test_x,y=y_pred,clf=classifier)

In [32]:
l= iter(test_x)

In [33]:
y=cl.predict([ [7.7, 2.6, 6.9, 2.3]])
y

array(['Iris-virginica'], dtype=object)

In [34]:
# confusion_matrix(Y,y)

In [ ]:
accuracy_score(y,t)